development:
  secret_key_base: b3879fb45a90ceb77491486a4be3cd5a147f064511ba25b01877b38e383e4fde60f0b6c26c0cbc7497e0a14f54603a4cb58c6ad0793e06363540920f4f3f82b7
  facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>
  bucket: <%= ENV['S3_BUCKET_NAME'] %>
  access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>

test:
  secret_key_base: 8e9f8add6e4e3d1ff383c989d7e824c2970c1b7f01bf4cd27fa77d32437d2997151626e8f291f4455559d0775c863fd2b5897e2e32b3d8c05fd744d574f3559a

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>
  bucket: <%= ENV['S3_BUCKET_NAME'] %>
  access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
